leader:
  credentialsPath: "test/fixtures/data/credentials.txt"
  url: "http://leader:8080"
  templatesPath: "test/fixtures/data/"
acme:
  isProduction: false
  #csrPath: "test/fixtures/test-renew-ssl.pryv.io.csr"
  email: tech@pryv.com
