leader:
  credentialsPath: "test/fixtures/data/credentials.txt"
  url: "http://leader:8080"
  templatesPath: "test/fixtures/data/"
acme:
  isProduction: false
  #csrPath: "test/fixtures/test-renew-ssl.pryv.io.csr"
  email: tech@pryv.com
  dnsRetryWaitMs: 10
  dnsRebootWaitMs: 10
  dnsRetriesCount: 60
  skipDnsChecks: false
logs:
  console:
    active: false
    level: "info"
  file:
    active: false
    path: "/app/log/ssl-certificate.log"
    level: info
    rotation:
      isActive: false
      days: 14
