name: SSL renewal deployment

on: 
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.13]

    - name: Login to the docker containers registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

     - name: Set tag
       id: set_tag
       run: |
-          SOURCE_TAG=$(git describe --abbrev=0 --tags)
           echo $SOURCE_TAG
           echo ::set-output name=SOURCE_TAG::$SOURCE_TAG

    - name: Build core image
      run: docker build -t pryvio/ssl-certificate:${{ steps.set_tag.outputs.SOURCE_TAG }} .

    - name: Upload new image to pryv registry
      run: docker images && docker push pryvio/ssl-certificate:${{ steps.set_tag.outputs.SOURCE_TAG }}