name: SSL renewal tests

on: push
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.4.1]

    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Download dependencies
      run: yarn
      
    - name: Run tests
      run: yarn test-logs